version: "3"
services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "7080:3000"
    volumes:
      - .:/src/backend

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: --auth
