version: "3"
services:
  web:
    platform: linux/amd64
    build: .
    ports:
      - "7080:3000"
    volumes:
      - .:/src/backend

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./data/db:/data/db
      - ./mongod.conf:/etc/mongod.conf
    ports:
      - "27017:27017"
    command: --config /etc/mongod.conf
